using System.Text.RegularExpressions;

namespace SeMaps.Extract.CSharp;

/// <summary>
/// Decides whether a source file (given as a root-relative, forward-slash path) is part of
/// the extractor's output, per PLAN_20260923_extractors_csharp.md "Исключения по умолчанию"
/// and "--include — фильтр по путям файлов результата".
/// </summary>
internal sealed class PathFilter
{
    private readonly List<string> _includePrefixes;
    private readonly List<Regex> _excludeGlobs;

    public PathFilter(IEnumerable<string> includeRelativePaths, IEnumerable<string> excludeGlobs)
    {
        _includePrefixes = includeRelativePaths
            .Select(NormalizeRelative)
            .Where(p => p.Length > 0)
            .ToList();
        _excludeGlobs = excludeGlobs.Select(GlobToRegex).ToList();
    }

    public static string NormalizeRelative(string path) => path.Replace('\\', '/').Trim('/');

    public bool IsIncluded(string relPath)
    {
        if (_includePrefixes.Count == 0)
        {
            return true;
        }

        foreach (var prefix in _includePrefixes)
        {
            if (relPath == prefix || relPath.StartsWith(prefix + "/", StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    public bool IsExcluded(string relPath, string? firstLines)
    {
        if (IsDefaultExcludedPath(relPath))
        {
            return true;
        }

        if (firstLines is not null && firstLines.Contains("<auto-generated", StringComparison.Ordinal))
        {
            return true;
        }

        foreach (var glob in _excludeGlobs)
        {
            if (glob.IsMatch(relPath))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsDefaultExcludedPath(string relPath)
    {
        var segments = relPath.Split('/');
        foreach (var segment in segments)
        {
            if (segment is "bin" or "obj")
            {
                return true;
            }
        }

        var fileName = segments[^1];
        if (fileName.EndsWith(".g.cs", StringComparison.Ordinal)) return true;
        if (fileName.EndsWith(".g.i.cs", StringComparison.Ordinal)) return true;
        if (fileName.EndsWith(".Designer.cs", StringComparison.Ordinal)) return true;
        if (fileName.EndsWith("AssemblyInfo.cs", StringComparison.Ordinal)) return true;
        if (fileName.StartsWith("GlobalUsings", StringComparison.Ordinal) && fileName.EndsWith(".cs", StringComparison.Ordinal)) return true;
        if (fileName.EndsWith(".generated.cs", StringComparison.Ordinal)) return true;

        return false;
    }

    private static Regex GlobToRegex(string glob)
    {
        var normalized = NormalizeRelative(glob);
        var pattern = "^" + Regex.Escape(normalized)
            .Replace(@"\*\*", ".*")
            .Replace(@"\*", "[^/]*")
            .Replace(@"\?", ".") + "$";
        return new Regex(pattern, RegexOptions.Compiled);
    }
}
