import type { DiagramEdge, DiagramElement } from "../model/types.js";
import { el, replaceChildren } from "../util/dom.js";
import { select } from "./fields.js";
import { SearchableSelect, type SearchableOption } from "./SearchableSelect.js";
import { resolveElementRelations, type ResolvedRelation } from "../model/relations-resolver.js";
import type { DiagramEditor } from "./DiagramEditor.js";
import { i18n } from "../workbench/i18n/I18nService.js";

export class EdgesPanel {
  private filter = "";
  private editingId: string | null = null;
  private confirmingDeleteId: string | null = null;

  constructor(
    private readonly body: HTMLElement,
    private readonly host: DiagramEditor,
  ) {}

  render(): void {
    const doc = this.host.canvas.model;
    const selection = this.host.canvas.selected;

    if (selection === null || doc === null) {
      replaceChildren(
        this.body,
        el("div", { class: "inspector-empty" }, [
          el("p", { class: "inspector-empty-icon", text: "🔗" }),
          el("p", { text: i18n.d.panels.relations.empty }),
        ]),
      );
      return;
    }

    if (selection.kind === "edge") {
      const edge = doc.edge(selection.id);
      if (edge === undefined) {
        replaceChildren(this.body, el("div", { class: "muted italic", text: i18n.d.panels.relations.notFound }));
        return;
      }
      this.renderSingleEdge(edge);
      return;
    }

    const element = doc.element(selection.id);
    if (element === undefined) {
      replaceChildren(this.body, el("div", { class: "muted italic", text: i18n.d.panels.relations.notFound }));
      return;
    }

    this.renderElementEdges(element);
  }

  private renderSingleEdge(edge: DiagramEdge): void {
    const doc = this.host.canvas.model;
    if (!doc) return;

    const fromEl = doc.element(edge.from);
    const toEl = doc.element(edge.to);

    const typeSelect = select(
      [
        ["call", i18n.d.panels.relations.callType],
        ["implements", i18n.d.panels.relations.implementsType],
        ["composes", i18n.d.panels.relations.composesType],
        ["extends", i18n.d.panels.relations.extendsType],
        ["event", i18n.d.panels.relations.eventType],
        ["storage", i18n.d.panels.relations.storageType],
        ["relates", i18n.d.panels.relations.relatesType],
      ],
      edge.type,
      (newType) => {
        edge.type = newType;
        (this.host as any).commit("edit-edge-type");
        this.host.canvas.render();
      },
    );

    const edgeStyles = this.host.canvas.styles.list("edge").map((s) => ({
      value: s.id,
      label: s.name || s.id,
      subtitle: s.id,
    }));

    const styleSelect = new SearchableSelect({
      options: [["", i18n.d.panels.properties.styleDefault], ...edgeStyles.map((s) => [s.value, s.label] as [string, string])],
      value: edge.styleId ?? "",
      searchPlaceholder: i18n.d.panels.properties.styleFilterPlaceholder,
      onChange: (val) => {
        edge.styleId = val || undefined;
        (this.host as any).commit("edit-edge-style");
        this.host.canvas.render();
      },
    });

    const labelInput = el("input", {
      type: "text",
      value: edge.label || "",
      placeholder: i18n.d.panels.relations.labelPlaceholder,
      on: {
        change: (e) => {
          const value = (e.target as HTMLInputElement).value;
          edge.label = value;
          doc.setText(edge.id, { name: value, description: value }, this.host.dataLang || "ru");
          (this.host as any).commit("edit-edge-label");
          this.host.canvas.render();
        },
      },
    });

    // A code-origin edge carries no text at all (ADR_20260831 §2.13); its
    // meaning is the type, regenerated by `sync` every run.
    const endLabelsField =
      edge.origin === "code"
        ? el("div", { class: "muted italic", text: i18n.d.panels.properties.edgeCodeOriginNotice })
        : el("div", { class: "grid-2" }, [
            el("label", { class: "field" }, [
              el("span", { class: "field-label", text: i18n.d.panels.properties.edgeFromLabelTitle }),
              el("input", {
                type: "text",
                value: edge.fromLabel ?? "",
                placeholder: i18n.d.panels.relations.fromLabelPlaceholder,
                on: {
                  change: (e) => {
                    const value = (e.target as HTMLInputElement).value;
                    edge.fromLabel = value;
                    doc.setText(edge.id, { fromLabel: value }, this.host.dataLang || "ru");
                    (this.host as any).commit("edit-edge-from-label");
                    this.host.canvas.render();
                  },
                },
              }),
            ]),
            el("label", { class: "field" }, [
              el("span", { class: "field-label", text: i18n.d.panels.properties.edgeToLabelTitle }),
              el("input", {
                type: "text",
                value: edge.toLabel ?? "",
                placeholder: i18n.d.panels.relations.toLabelPlaceholder,
                on: {
                  change: (e) => {
                    const value = (e.target as HTMLInputElement).value;
                    edge.toLabel = value;
                    doc.setText(edge.id, { toLabel: value }, this.host.dataLang || "ru");
                    (this.host as any).commit("edit-edge-to-label");
                    this.host.canvas.render();
                  },
                },
              }),
            ]),
          ]);

    replaceChildren(
      this.body,
      el("div", { class: "panel-section" }, [
        el("div", { class: "field-row" }, [
          el("span", { class: "field-label accent", text: i18n.d.panels.properties.edgeLabelTitle }),
          el("span", { class: "mono muted", text: edge.id }),
        ]),
        el("div", { class: "field-row" }, [
          el("span", { class: "muted", text: "Откуда / From:" }),
          el("span", { class: "input-strong", text: fromEl?.label || edge.from }),
        ]),
        el("div", { class: "field-row" }, [
          el("span", { class: "muted", text: "Куда / To:" }),
          el("span", { class: "input-strong", text: toEl?.label || edge.to }),
        ]),
        el("label", { class: "field" }, [
          el("span", { class: "field-label", text: i18n.d.panels.properties.edgeTypeTitle }),
          typeSelect,
        ]),
        el("label", { class: "field" }, [
          el("span", { class: "field-label", text: i18n.d.panels.properties.styleTitle }),
          styleSelect.root,
        ]),
        el("label", { class: "field" }, [
          el("span", { class: "field-label", text: i18n.d.panels.properties.edgeLabelTitle }),
          labelInput,
        ]),
        endLabelsField,
        el("button", {
          class: "btn btn-danger full",
          text: i18n.d.panels.properties.deleteEdgeBtn,
          on: {
            click: () => {
              doc.removeEdge(edge.id);
              (this.host as any).commit("delete-edge");
              this.host.canvas.select(null);
            },
          },
        }),
      ]),
    );
  }

  private renderElementEdges(element: DiagramElement): void {
    const doc = this.host.canvas.model;
    if (!doc) return;

    const summary = resolveElementRelations(doc, element);
    const relationsList = summary.items;
    const visibleCount = summary.visible;
    const totalCount = summary.total;

    const needle = this.filter.trim().toLowerCase();
    const filtered = relationsList.filter((r) => {
      if (needle === "") return true;
      const otherId = r.from === element.id ? r.to : r.from;
      const otherEl = doc.element(otherId);
      const otherLabel = String(otherEl?.label || otherId);
      const rType = String(r.type ?? "");
      const rLabel = String(r.label ?? "");
      const rStyle = String(r.styleId ?? "");
      return (
        otherLabel.toLowerCase().includes(needle) ||
        rType.toLowerCase().includes(needle) ||
        rLabel.toLowerCase().includes(needle) ||
        rStyle.toLowerCase().includes(needle)
      );
    });

    const rows = filtered.map((item) => this.renderRelationRow(element, item));

    const filterInput = el("input", {
      type: "text",
      placeholder: i18n.d.panels.relations.searchPlaceholder,
      value: this.filter,
      on: {
        input: (e) => {
          this.filter = (e.target as HTMLInputElement).value;
          this.render();
        },
      },
    });

    const header = el("div", { class: "edge-table-header" }, [
      el("span", { text: i18n.d.panels.relations.title }),
      el("span", { text: i18n.d.panels.properties.typeTitle }),
      el("span", { text: i18n.d.panels.properties.styleTitle }),
      el("span", { text: "✓", attrs: { style: "text-align: center;" } }),
      el("span", { text: "" }),
      el("span", { text: "" }),
    ]);

    const addSection = this.renderAddSection(element);

    replaceChildren(
      this.body,
      el("div", { class: "panel-section" }, [
        el("div", { class: "field-row" }, [
          el("span", { class: "field-label accent", text: `${i18n.d.panels.relations.title}: ${element.label}` }),
          el("span", { class: "mono chip", text: i18n.format(i18n.d.panels.relations.countSummary, { total: totalCount, active: visibleCount }) }),
        ]),
        filterInput,
        header,
        el(
          "div",
          { class: "edge-list", attrs: { style: "max-height: 320px; gap: 3px;" } },
          rows.length === 0
            ? [el("div", { class: "muted italic", text: i18n.d.panels.relations.notFound })]
            : rows,
        ),
        addSection,
      ]),
    );
  }

  private renderRelationRow(element: DiagramElement, item: ResolvedRelation): HTMLElement {
    const doc = this.host.canvas.model;
    if (!doc) return el("div");

    const isOutgoing = item.from === element.id;
    const otherId = isOutgoing ? item.to : item.from;
    const otherEl = doc.element(otherId);
    const otherName = otherEl?.label || otherId;

    const isEditing = this.editingId === item.id;
    const isConfirmingDelete = this.confirmingDeleteId === item.id;

    const checkbox = el("input", {
      type: "checkbox",
      title: item.visible ? "Скрыть связь с холста" : "Отобразить связь на холсте",
      on: {
        change: (e) => {
          const checked = (e.target as HTMLInputElement).checked;
          if (checked) {
            doc.addEdge({
              id: item.id,
              from: item.from,
              to: item.to,
              type: item.type,
              label: item.label,
              styleId: item.styleId,
            });
            (this.host as any).commit("show-edge");
          } else {
            doc.removeEdge(item.id);
            (this.host as any).commit("hide-edge");
          }
          this.render();
        },
      },
    });
    (checkbox as HTMLInputElement).checked = item.visible;

    const labelSpan = el("div", {
      class: "edge-col-target",
      title: `${isOutgoing ? "Исходящая к" : "Входящая от"} ${otherName} (кликните для перехода)`,
      on: {
        click: () => {
          if (otherEl) {
            this.host.canvas.select(otherEl.id);
          }
        },
      },
    }, [
      el("span", { class: "mono", text: isOutgoing ? "➔" : "⬅", attrs: { style: "opacity: 0.7; font-size: 10px;" } }),
      el("span", { class: "input-strong", text: otherName }),
      item.label ? el("span", { class: "muted mono", text: `«${item.label}»`, attrs: { style: "font-size: 10px;" } }) : null,
    ]);

    const typeCol = el("div", { class: "edge-col-type" }, [
      el("span", {
        class: "badge chip",
        text: item.type,
        title: `Тип связи: ${item.type}`,
        attrs: { style: "font-size: 9.5px; padding: 1px 4px;" },
      }),
    ]);

    const styleCol = el("div", { class: "edge-col-style" }, [
      el("span", {
        class: "mono muted",
        text: item.styleId ? item.styleId.replace(/^relation\./, "") : "auto",
        title: `Стиль связи: ${item.styleId ?? "по типу"}`,
        attrs: { style: "font-size: 9.5px;" },
      }),
    ]);

    const editBtn = el("button", {
      class: "btn-icon",
      text: "✏️",
      title: "Редактировать связь",
      on: {
        click: () => {
          this.editingId = isEditing ? null : item.id;
          this.confirmingDeleteId = null;
          this.render();
        },
      },
    });

    const deleteBtn = el("button", {
      class: `btn-icon${isConfirmingDelete ? " is-confirm" : " danger"}`,
      text: isConfirmingDelete ? "Да?" : "✕",
      title: isConfirmingDelete ? "Нажмите для подтверждения удаления" : "Удалить связь",
      on: {
        click: () => {
          if (!isConfirmingDelete) {
            this.confirmingDeleteId = item.id;
            this.render();
            return;
          }
          if (item.visible) {
            doc.removeEdge(item.id);
          }
          const rels = doc.relations;
          if (Array.isArray(rels)) {
            const idx = rels.findIndex((r) => r.id === item.id);
            if (idx >= 0) rels.splice(idx, 1);
          }
          this.confirmingDeleteId = null;
          (this.host as any).commit("delete-relation");
          this.render();
        },
      },
    });

    const row = el(
      "div",
      {
        class: `edge-table-row${item.visible ? "" : " is-hidden-edge"}`,
      },
      [
        labelSpan,
        typeCol,
        styleCol,
        el("div", { class: "edge-col-check" }, [checkbox]),
        el("div", { class: "edge-col-action" }, [editBtn]),
        el("div", { class: "edge-col-action" }, [deleteBtn]),
      ],
    );

    if (isEditing) {
      const typeSel = select(
        [
          ["call", "Вызов (call)"],
          ["implements", "Реализует (implements)"],
          ["composes", "Компонует (composes)"],
          ["extends", "Расширяет (extends)"],
          ["event", "Событие (event)"],
          ["storage", "Хранилище (storage)"],
          ["relates", "Связан (relates)"],
        ],
        item.type,
        () => undefined,
      );

      const edgeStyles = this.host.canvas.styles.list("edge").map((s) => ({
        value: s.id,
        label: s.name || s.id,
        subtitle: s.id,
      }));

      const styleSel = new SearchableSelect({
        options: [["", "По умолчанию (по типу)"], ...edgeStyles.map((s) => [s.value, s.label] as [string, string])],
        value: item.styleId ?? "",
        searchPlaceholder: "Поиск стиля связи…",
        onChange: () => undefined,
      });

      const lblInput = el("input", { type: "text", value: item.label, placeholder: "Подпись связи…" });

      const editBox = el("div", {
        attrs: { style: "display: flex; flex-direction: column; gap: 6px; padding: 8px; margin-top: 2px; margin-bottom: 4px; background: var(--panel); border: 1px solid var(--line); border-radius: 6px;" },
      }, [
        el("div", { class: "grid-2" }, [typeSel, styleSel.root]),
        lblInput,
        el("div", { attrs: { style: "display: flex; gap: 6px; justify-content: flex-end;" } }, [
          el("button", {
            class: "btn btn-small",
            text: "Отмена",
            on: {
              click: () => {
                this.editingId = null;
                this.render();
              },
            },
          }),
          el("button", {
            class: "btn btn-primary btn-small",
            text: "Сохранить",
            on: {
              click: () => {
                item.type = typeSel.value;
                item.label = lblInput.value;
                const pickedStyle = (styleSel as any).currentValue;
                item.styleId = pickedStyle || undefined;

                if (item.edge) {
                  item.edge.type = item.type;
                  item.edge.label = item.label;
                  item.edge.styleId = item.styleId;
                }
                if (item.raw) {
                  item.raw.type = item.type;
                  item.raw.relation = item.type;
                  item.raw.label = item.label;
                  item.raw.styleId = item.styleId;
                }
                this.editingId = null;
                (this.host as any).commit("update-relation");
                this.render();
              },
            },
          }),
        ]),
      ]);

      return el("div", { attrs: { style: "display: flex; flex-direction: column;" } }, [row, editBox]);
    }

    return row;
  }

  private renderAddSection(element: DiagramElement): HTMLElement {
    const doc = this.host.canvas.model;
    if (!doc) return el("div");

    const allLeaves = doc.leaves().filter((n) => n.id !== element.id);
    const targetOptions: SearchableOption[] = allLeaves.map((n) => {
      const parentZone = n.parent ? doc.element(n.parent.id)?.label : undefined;
      return {
        value: n.id,
        label: n.label,
        subtitle: parentZone ? `в ${parentZone}` : n.id,
        badge: n.type,
      };
    });

    let selectedTarget = "";
    const targetSelect = new SearchableSelect({
      options: targetOptions,
      value: "",
      searchPlaceholder: i18n.d.panels.relations.searchPlaceholder,
      placeholder: i18n.d.panels.relations.chooseTarget,
      onChange: (val) => {
        selectedTarget = val;
      },
    });

    const typeSelect = select(
      [
        ["call", i18n.d.panels.relations.callType],
        ["implements", i18n.d.panels.relations.implementsType],
        ["composes", i18n.d.panels.relations.composesType],
        ["extends", i18n.d.panels.relations.extendsType],
        ["event", i18n.d.panels.relations.eventType],
        ["storage", i18n.d.panels.relations.storageType],
        ["relates", i18n.d.panels.relations.relatesType],
      ],
      "call",
      () => undefined,
    );

    const edgeStyles = this.host.canvas.styles.list("edge").map((s) => ({
      value: s.id,
      label: s.name || s.id,
      subtitle: s.id,
    }));

    let selectedStyle = "";
    const styleSelect = new SearchableSelect({
      options: [["", i18n.d.panels.properties.styleDefault], ...edgeStyles.map((s) => [s.value, s.label] as [string, string])],
      value: "",
      searchPlaceholder: i18n.d.panels.properties.styleFilterPlaceholder,
      placeholder: i18n.d.panels.properties.styleDefault,
      onChange: (val) => {
        selectedStyle = val;
      },
    });

    const labelInput = el("input", { type: "text", placeholder: i18n.d.panels.relations.labelPlaceholder });

    return el("div", { class: "panel", attrs: { style: "flex-direction: column; align-items: stretch; gap: 6px; margin-top: 8px;" } }, [
      el("div", { class: "field-label accent", text: i18n.d.panels.relations.addNewHeader }),
      targetSelect.root,
      el("div", { class: "grid-2" }, [typeSelect, styleSelect.root]),
      el("div", { class: "field-row gap" }, [
        labelInput,
        el("button", {
          class: "btn btn-primary",
          text: i18n.d.panels.relations.connectBtn,
          on: {
            click: () => {
              if (!selectedTarget) return;
              const edgeId = `edge_${Date.now()}`;
              doc.addEdge({
                id: edgeId,
                from: element.id,
                to: selectedTarget,
                type: typeSelect.value,
                label: labelInput.value,
                styleId: selectedStyle || undefined,
              });
              (this.host as any).commit("add-edge");
              this.render();
            },
          },
        }),
      ]),
    ]);
  }
}
