import { I18nService } from "../workbench/i18n/I18nService.js";

/**
 * Texts of the tool modes (Extractors, Project). Kept apart from the
 * editor's dictionary.
 */
const ru = {
  navEditor: "Схемы",
  navExtract: "Экстракторы",
  navSetup: "Проект",
  refresh: "Обновить",
  refreshHint: "Перечитать с хоста",
  noProjectFile: "Хост запущен с --workspace: нет файла .semaps, экстракторов и настроек нет.",
  loading: "Загрузка…",
  // setup
  setupTitle: "Настройки проекта",
  setupHint: "Файл {file}. Комментарии в нём сохраняются. Рабочая папка, корень кода и порт вступают в силу после перезапуска semaps.",
  name: "Имя",
  workspace: "Рабочая папка",
  sourceRoot: "Корень кода",
  port: "Порт",
  save: "Сохранить",
  saved: "Сохранено",
  toolsTitle: "Инструменты",
  shipped: "Рядом с semaps",
  none: "нет",
  runtimeMissing: "не найден",
  // extract
  extractTitle: "Экстракторы",
  extractHint: "Извлечь → посмотреть отчёт сверки → записать. Записываются ровно те факты, по которым показан отчёт.",
  addExtractor: "Добавить экстрактор",
  newId: "id нового экстрактора (латиница, цифры, -)",
  language: "Язык",
  modelProject: "Модельный проект",
  root: "Корень",
  include: "Включить",
  exclude: "Исключить",
  edgeKinds: "Виды связей",
  watch: "Следить за исходниками",
  watchHint: "При изменении исходников экстрактор запускается заново и обновляется только граф; реестр меняет только сверка.",
  runTriggerWatch: "слежение",
  listHint: "через запятую",
  command: "Команда (только в файле)",
  extractorFound: "найден",
  extractorMissing: "не найден",
  remove: "Удалить",
  confirmRemove: "Удалить экстрактор «{id}» из .semaps?",
  extract: "Извлечь",
  running: "Идёт извлечение…",
  lastRun: "Последний прогон",
  symbols: "символов",
  edges: "рёбер",
  failed: "ошибка",
  dryRun: "Проверить сверку",
  apply: "Записать в реестр",
  noRenames: "Переименования — как «пропало + новое»",
  reportEmpty: "Реестр совпадает с кодом — записывать нечего.",
  written: "Записано",
  openEditor: "Открыть схемы",
  groups: {
    broken: "сломано",
    ambiguous: "неоднозначно",
    renames: "переименование?",
    gone: "лишнее",
    added: "не хватает",
    changed: "изменилось",
  },
  // mcp
  navMcp: "MCP",
  mcpTitle: "Карта кода для вашего ИИ-агента",
  mcpLead:
    "semaps mcp — MCP-сервер, через который Claude Code, Cursor, Copilot и другие агенты читают и правят эту карту сами. Не нужно объяснять агенту формат файлов: он получает инструменты, а правила контракта держит сервер.",
  mcpWhyTitle: "Что это даёт",
  mcpWhy: [
    "Агент отвечает на вопросы об архитектуре по реестру, а не перечитывает весь код: «кто держит VmProgram», «что зависит от этой сборки».",
    "Агент сам пишет описания, подписи связей и переводы — всё помечается как авторское, с датой.",
    "После правки кода агент запускает извлечение и сверку и объясняет, что изменилось на схемах.",
    "Правила соблюдаются всегда: id выдаёт сервер, ничего не удаляется, раскладку видов агент трогает только по вашей просьбе.",
  ],
  mcpStateTitle: "Подключение в этом проекте",
  mcpConfigured: "Подключено: {file} запускает semaps mcp (запись «{entry}»). Агенту достаточно открыть этот репозиторий.",
  mcpNotConfigured: "Пока не подключено: в корне проекта нет записи semaps в {file}.",
  mcpInstall: "Подключить",
  mcpInstallHint: "Допишет запись semaps в {file} в корне проекта; другие серверы в файле останутся.",
  mcpNotOnPath: "semaps не найден в PATH: клиент агента его не запустит. Установите semaps (install.cmd) или впишите полный путь в command.",
  mcpManual: "Или вручную — {file} в корне проекта:",
  mcpCopy: "Копировать",
  mcpCopied: "Скопировано",
  mcpPlayTitle: "Песочница",
  mcpPlayHint: "Вызов инструмента на этом проекте так, как его делает агент: видно, что улетает и что прилетает. Для отладки и развития сервера.",
  mcpPlayTool: "Инструмент",
  mcpPlayArgs: "Аргументы (JSON)",
  mcpPlayParams: "Параметры",
  mcpPlayCall: "Вызвать",
  mcpPlayWrite: "Инструмент записи: вызов по-настоящему изменит реестр проекта.",
  mcpPlayWriteOk: "Понимаю, вызвать",
  mcpPlayBadJson: "Аргументы — не JSON-объект: {error}",
  mcpPlayOk: "✓ ответ за {ms} мс",
  mcpPlayToolError: "✗ инструмент вернул ошибку, {ms} мс",
  mcpPlayFailed: "✗ вызов не прошёл: {error}",
  mcpPlayOut: "→ отправлено",
  mcpPlayIn: "← получено",
  mcpPlayContent: "Содержимое ответа",
  mcpRead: "чтение",
  mcpWrite: "запись",
  mcpToolsTitle: "Инструменты сервера",
  // mcp settings (step 5)
  mcpSettingsTitle: "Настройки для агента",
  mcpSettingsHint: "Что получает агент, подключившийся через MCP — набор инструментов, подробность их описаний и умолчания графа. Пример справа меняется сразу, ещё до сохранения.",
  mcpToolSet: "Набор инструментов",
  mcpToolSetOne: "один общий",
  mcpToolSetOneFor: "для сильной модели: сама выбирает связи и глубину",
  mcpToolSetNarrow: "узкие, по одному вопросу",
  mcpToolSetNarrowFor: "для небольшой модели: имя вопроса — уже выбор связей",
  mcpDescLevel: "Подробность описаний",
  mcpDescBrief: "кратко",
  mcpDescBriefHint: "что делает, один пример",
  mcpDescStandard: "обычно",
  mcpDescStandardHint: "параметры, примеры «вопрос → запрос»",
  mcpDescFull: "полностью",
  mcpDescFullHint: "всё: словарь связей, lift, fanout, язык шаблонов",
  mcpCost: "{bytes} байт, ≈ {tokens} токенов",
  mcpDefaultsTitle: "Умолчания инструмента",
  mcpDefaultFormat: "Формат ответа",
  mcpDefaultFormatHint: "В каком виде get_graph отвечает по умолчанию, если агент не попросил другой.",
  mcpDefaultListCap: "Порог списка",
  mcpDefaultListCapHint: "Сколько имён или строк одной связи печатать до «+N»; запрос агента может задать своё.",
  mcpDefaultLimit: "Предел узлов",
  mcpDefaultLimitHint: "Сколько узлов возвращать без around и container; запрос агента может задать своё.",
  mcpPreviewTitle: "Что получит агент",
  mcpPreviewHint: "Инструкции сервера, затем каждый инструмент с именем и полным текстом описания — ровно так, как их увидит агент.",
  mcpPreviewSize: "{bytes} байт, ≈ {tokens} токенов",
  mcpUnsaved: "Есть несохранённые изменения",
  mcpSaveTitle: "Сохранение",
  mcpSaveNote: [
    "Умолчания графа (формат, порог списка, предел узлов) действуют со следующего вызова.",
    "Новые сеансы получают новый набор и уровень описаний сразу.",
    "Уже открытый сеанс получит новые инструменты, когда его клиент в следующий раз спросит список.",
    "Агент, подключённый через semaps mcp, должен перезапустить сеанс.",
  ],
  mcpSaved: "Сохранено.",
  mcpAskTitle: "Что попросить у агента",
  mcpAsk: [
    "«Какие классы держат VmProgram и через какие поля?»",
    "«Опиши все сборки проекта одной строкой каждую, на русском и английском»",
    "«Я переименовал поле — сверь карту и подтверди переименование»",
    "«Покажи на виде Операции связи injects для VmController»",
    "«Сделай зоны в v_ops#z_transform как v_ops#z_tr_undistort» (ссылку копирует «🔗» в свойствах или меню блока)",
  ],
  // graph
  navGraph: "Граф",
  graphProject: "Проект",
  graphNoFactsNotice: "Ни один экстрактор ещё не запускался — граф показывает только модель.",
  graphOpenExtractors: "Открыть Экстракторы",
  graphSearchPlaceholder: "Поиск по имени…",
  graphColorBy: "Цвет по",
  graphColorKind: "вид символа",
  graphColorContainer: "контейнер",
  graphColorNamespace: "пространство имён",
  graphColorPresence: "род узла",
  graphLayout: "Раскладка",
  graphLayoutForce: "силовая",
  graphLayoutFolder: "по папкам",
  graphLayoutNamespace: "по пространствам имён",
  graphLayoutCommunity: "по сообществам",
  graphLayoutContainer: "по контейнерам",
  graphRestartLayout: "Пересчитать раскладку",
  graphLegend: "Легенда",
  graphFilters: "Фильтры",
  graphFilterEdgeKinds: "Виды рёбер",
  graphFilterSymbolKinds: "Виды символов",
  graphFilterVisibility: "Видимость",
  graphFilterPresence: "Род узла",
  graphFilterContainer: "Контейнер",
  graphPresenceCode: "только в коде",
  graphPresenceModel: "только в модели",
  graphPresenceBoth: "код + модель",
  graphAnyContainer: "любой",
  graphPanelTitle: "Свойства",
  graphPanelEmpty: "Выберите узел, чтобы увидеть его свойства.",
  graphKind: "Вид",
  graphNativeKind: "Родной вид",
  graphVisibility: "Видимость",
  graphFile: "Файл",
  graphEntity: "Сущность",
  graphContainers: "Контейнеры",
  graphPresence: "Род узла",
  graphEdgesOf: "Связи",
  graphOpenSource: "Открыть исходник",
  graphStats: "{nodes} узлов, {edges} рёбер",
  graphShowMissing: "показывать пропавшие",
  graphHiddenMissing: "скрыто: {nodes} узлов, {edges} рёбер",
  graphRunFailedNotice: "Последний прогон экстрактора «{extractor}» не удался — граф показывает факты предыдущего прогона.",
  graphLiveDiff: "+{addedNodes}/−{removedNodes} узлов, +{addedEdges}/−{removedEdges} рёбер",
};

type Strings = typeof ru;

const en: Strings = {
  navEditor: "Diagrams",
  navExtract: "Extractors",
  navSetup: "Project",
  refresh: "Refresh",
  refreshHint: "Read again from the host",
  noProjectFile: "The host was started with --workspace: no .semaps file, so no extractors or settings.",
  loading: "Loading…",
  setupTitle: "Project settings",
  setupHint: "File {file}. Its comments are kept. Workspace, source root and port apply after semaps restarts.",
  name: "Name",
  workspace: "Workspace",
  sourceRoot: "Source root",
  port: "Port",
  save: "Save",
  saved: "Saved",
  toolsTitle: "Tools",
  shipped: "Beside semaps",
  none: "none",
  runtimeMissing: "not found",
  extractTitle: "Extractors",
  extractHint: "Extract → review the sync report → write. Exactly the facts the report was made from are written.",
  addExtractor: "Add extractor",
  newId: "id of the new extractor (latin, digits, -)",
  language: "Language",
  modelProject: "Model project",
  root: "Root",
  include: "Include",
  exclude: "Exclude",
  edgeKinds: "Edge kinds",
  watch: "Watch sources",
  watchHint: "A source change reruns the extractor and refreshes the graph only; the registry is changed by sync alone.",
  runTriggerWatch: "watch",
  listHint: "comma-separated",
  command: "Command (file only)",
  extractorFound: "found",
  extractorMissing: "not found",
  remove: "Remove",
  confirmRemove: "Remove extractor “{id}” from .semaps?",
  extract: "Extract",
  running: "Extracting…",
  lastRun: "Last run",
  symbols: "symbols",
  edges: "edges",
  failed: "failed",
  dryRun: "Check the sync",
  apply: "Write to the registry",
  noRenames: "Treat renames as gone + new",
  reportEmpty: "The registry matches the code — nothing to write.",
  written: "Written",
  openEditor: "Open diagrams",
  groups: {
    broken: "broken",
    ambiguous: "ambiguous",
    renames: "rename?",
    gone: "gone",
    added: "missing",
    changed: "changed",
  },
  // mcp
  navMcp: "MCP",
  mcpTitle: "A code map for your AI agent",
  mcpLead:
    "semaps mcp is an MCP server through which Claude Code, Cursor, Copilot and other agents read and edit this map themselves. No need to explain the file format: the agent gets tools, the server keeps the contract's rules.",
  mcpWhyTitle: "What it gives you",
  mcpWhy: [
    "The agent answers architecture questions from the registry instead of rereading the code: who holds VmProgram, what depends on this assembly.",
    "The agent writes descriptions, relation labels and translations itself — all marked authored, with a date.",
    "After a code change the agent runs extraction and sync and explains what changed on the diagrams.",
    "The rules always hold: ids come from the server, nothing is deleted, view layout is touched only when you ask.",
  ],
  mcpStateTitle: "Connection in this project",
  mcpConfigured: "Connected: {file} starts semaps mcp (entry “{entry}”). An agent only has to open this repository.",
  mcpNotConfigured: "Not connected yet: no semaps entry in {file} at the project root.",
  mcpInstall: "Connect",
  mcpInstallHint: "Adds the semaps entry to {file} at the project root; other servers in the file stay.",
  mcpNotOnPath: "semaps is not on PATH: the agent's client will not start it. Install semaps (install.cmd) or write the full path in command.",
  mcpManual: "Or by hand — {file} at the project root:",
  mcpCopy: "Copy",
  mcpCopied: "Copied",
  mcpPlayTitle: "Sandbox",
  mcpPlayHint: "Call a tool on this project the way an agent does, and see what goes out and what comes back. For debugging and growing the server.",
  mcpPlayTool: "Tool",
  mcpPlayArgs: "Arguments (JSON)",
  mcpPlayParams: "Parameters",
  mcpPlayCall: "Call",
  mcpPlayWrite: "A writing tool: the call really changes the project's registry.",
  mcpPlayWriteOk: "I understand, call it",
  mcpPlayBadJson: "Arguments are not a JSON object: {error}",
  mcpPlayOk: "✓ answered in {ms} ms",
  mcpPlayToolError: "✗ the tool returned an error, {ms} ms",
  mcpPlayFailed: "✗ the call failed: {error}",
  mcpPlayOut: "→ sent",
  mcpPlayIn: "← received",
  mcpPlayContent: "Response content",
  mcpRead: "read",
  mcpWrite: "write",
  mcpToolsTitle: "Server tools",
  // mcp settings (step 5)
  mcpSettingsTitle: "Settings for the agent",
  mcpSettingsHint: "What an agent gets when it connects over MCP — the tool set, how much its descriptions say, and the graph defaults. The preview on the right changes at once, before saving.",
  mcpToolSet: "Tool set",
  mcpToolSetOne: "one shared tool",
  mcpToolSetOneFor: "for a strong model: it picks the relations and depth itself",
  mcpToolSetNarrow: "narrow, one per question",
  mcpToolSetNarrowFor: "for a small model: the tool's name is already the choice of relations",
  mcpDescLevel: "Description detail",
  mcpDescBrief: "brief",
  mcpDescBriefHint: "what it does, one example",
  mcpDescStandard: "standard",
  mcpDescStandardHint: "parameters, “question → request” examples",
  mcpDescFull: "full",
  mcpDescFullHint: "everything: the relation vocabulary, lift, fanout, the template language",
  mcpCost: "{bytes} bytes, ≈ {tokens} tokens",
  mcpDefaultsTitle: "Tool defaults",
  mcpDefaultFormat: "Answer format",
  mcpDefaultFormatHint: "The shape get_graph answers in by default, unless the agent asks for another.",
  mcpDefaultListCap: "List cap",
  mcpDefaultListCapHint: "How many names or lines of one relation to print before “+N”; the agent's own request can override it.",
  mcpDefaultLimit: "Node limit",
  mcpDefaultLimitHint: "How many nodes to return with no around and no container; the agent's own request can override it.",
  mcpPreviewTitle: "What the agent will get",
  mcpPreviewHint: "The server's instructions, then every tool with its name and full description text — exactly as the agent will receive them.",
  mcpPreviewSize: "{bytes} bytes, ≈ {tokens} tokens",
  mcpUnsaved: "There are unsaved changes",
  mcpSaveTitle: "Saving",
  mcpSaveNote: [
    "The graph defaults (format, list cap, node limit) apply from the next call.",
    "New sessions get the new tool set and description level at once.",
    "A session already open gets the new tools once its client asks for the list again.",
    "An agent connected through semaps mcp needs its session restarted.",
  ],
  mcpSaved: "Saved.",
  mcpAskTitle: "What to ask the agent",
  mcpAsk: [
    "“Which classes hold VmProgram, and through which fields?”",
    "“Describe every assembly of the project in one line, in Russian and English”",
    "“I renamed a field — sync the map and confirm the rename”",
    "“Show the injects relations of VmController on the Operations view”",
    "“Lay out the zones in v_ops#z_transform like v_ops#z_tr_undistort” (the link is copied by “🔗” in Properties or the block menu)",
  ],
  // graph
  navGraph: "Graph",
  graphProject: "Project",
  graphNoFactsNotice: "No extractor has run yet — the graph shows the model only.",
  graphOpenExtractors: "Open Extractors",
  graphSearchPlaceholder: "Search by name…",
  graphColorBy: "Colour by",
  graphColorKind: "symbol kind",
  graphColorContainer: "container",
  graphColorNamespace: "namespace",
  graphColorPresence: "presence",
  graphLayout: "Layout",
  graphLayoutForce: "force",
  graphLayoutFolder: "by folder",
  graphLayoutNamespace: "by namespace",
  graphLayoutCommunity: "by community",
  graphLayoutContainer: "by container",
  graphRestartLayout: "Restart layout",
  graphLegend: "Legend",
  graphFilters: "Filters",
  graphFilterEdgeKinds: "Edge kinds",
  graphFilterSymbolKinds: "Symbol kinds",
  graphFilterVisibility: "Visibility",
  graphFilterPresence: "Presence",
  graphFilterContainer: "Container",
  graphPresenceCode: "code only",
  graphPresenceModel: "model only",
  graphPresenceBoth: "code + model",
  graphAnyContainer: "any",
  graphPanelTitle: "Properties",
  graphPanelEmpty: "Select a node to see its properties.",
  graphKind: "Kind",
  graphNativeKind: "Native kind",
  graphVisibility: "Visibility",
  graphFile: "File",
  graphEntity: "Entity",
  graphContainers: "Containers",
  graphPresence: "Presence",
  graphEdgesOf: "Edges",
  graphOpenSource: "Open source",
  graphStats: "{nodes} nodes, {edges} edges",
  graphShowMissing: "show missing",
  graphHiddenMissing: "hidden: {nodes} nodes, {edges} edges",
  graphRunFailedNotice: "The newest run of extractor “{extractor}” failed — the graph shows the facts of the run before it.",
  graphLiveDiff: "+{addedNodes}/−{removedNodes} nodes, +{addedEdges}/−{removedEdges} edges",
};

export const t: Strings = I18nService.get().currentLanguage === "en" ? en : ru;

export function fmt(text: string, values: Record<string, string>): string {
  return text.replace(/\{(\w+)\}/g, (_, k: string) => values[k] ?? "");
}
