import { I18nService } from "../workbench/i18n/I18nService.js";

/**
 * Texts of the tool modes (Extractors, Project). Kept apart from the
 * editor's dictionary.
 */
const ru = {
  navEditor: "Схемы",
  navExtract: "Экстракторы",
  navSetup: "Проект",
  refresh: "Обновить",
  refreshHint: "Перечитать с хоста",
  noProjectFile: "Хост запущен с --workspace: нет файла .semaps, экстракторов и настроек нет.",
  loading: "Загрузка…",
  // setup
  setupTitle: "Настройки проекта",
  setupHint: "Файл {file}. Комментарии в нём сохраняются. Рабочая папка, корень кода и порт вступают в силу после перезапуска semaps.",
  name: "Имя",
  workspace: "Рабочая папка",
  sourceRoot: "Корень кода",
  port: "Порт",
  save: "Сохранить",
  saved: "Сохранено",
  toolsTitle: "Инструменты",
  shipped: "Рядом с semaps",
  none: "нет",
  runtimeMissing: "не найден",
  // extract
  extractTitle: "Экстракторы",
  extractHint: "Извлечь → посмотреть отчёт сверки → записать. Записываются ровно те факты, по которым показан отчёт.",
  addExtractor: "Добавить экстрактор",
  newId: "id нового экстрактора (латиница, цифры, -)",
  language: "Язык",
  modelProject: "Модельный проект",
  root: "Корень",
  include: "Включить",
  exclude: "Исключить",
  edgeKinds: "Виды связей",
  listHint: "через запятую",
  command: "Команда (только в файле)",
  extractorFound: "найден",
  extractorMissing: "не найден",
  remove: "Удалить",
  confirmRemove: "Удалить экстрактор «{id}» из .semaps?",
  extract: "Извлечь",
  running: "Идёт извлечение…",
  lastRun: "Последний прогон",
  symbols: "символов",
  edges: "рёбер",
  failed: "ошибка",
  dryRun: "Проверить сверку",
  apply: "Записать в реестр",
  noRenames: "Переименования — как «пропало + новое»",
  reportEmpty: "Реестр совпадает с кодом — записывать нечего.",
  written: "Записано",
  openEditor: "Открыть схемы",
  groups: {
    broken: "сломано",
    ambiguous: "неоднозначно",
    renames: "переименование?",
    gone: "лишнее",
    added: "не хватает",
    changed: "изменилось",
  },
  // mcp
  navMcp: "MCP",
  mcpTitle: "Карта кода для вашего ИИ-агента",
  mcpLead:
    "semaps mcp — MCP-сервер, через который Claude Code, Cursor, Copilot и другие агенты читают и правят эту карту сами. Не нужно объяснять агенту формат файлов: он получает инструменты, а правила контракта держит сервер.",
  mcpWhyTitle: "Что это даёт",
  mcpWhy: [
    "Агент отвечает на вопросы об архитектуре по реестру, а не перечитывает весь код: «кто держит VmProgram», «что зависит от этой сборки».",
    "Агент сам пишет описания, подписи связей и переводы — всё помечается как авторское, с датой.",
    "После правки кода агент запускает извлечение и сверку и объясняет, что изменилось на схемах.",
    "Правила соблюдаются всегда: id выдаёт сервер, ничего не удаляется, раскладку видов агент трогает только по вашей просьбе.",
  ],
  mcpStateTitle: "Подключение в этом проекте",
  mcpConfigured: "Подключено: {file} запускает semaps mcp (запись «{entry}»). Агенту достаточно открыть этот репозиторий.",
  mcpNotConfigured: "Пока не подключено: в корне проекта нет записи semaps в {file}.",
  mcpInstall: "Подключить",
  mcpInstallHint: "Допишет запись semaps в {file} в корне проекта; другие серверы в файле останутся.",
  mcpNotOnPath: "semaps не найден в PATH: клиент агента его не запустит. Установите semaps (install.cmd) или впишите полный путь в command.",
  mcpManual: "Или вручную — {file} в корне проекта:",
  mcpCopy: "Копировать",
  mcpCopied: "Скопировано",
  mcpPlayTitle: "Песочница",
  mcpPlayHint: "Вызов инструмента на этом проекте так, как его делает агент: видно, что улетает и что прилетает. Для отладки и развития сервера.",
  mcpPlayTool: "Инструмент",
  mcpPlayArgs: "Аргументы (JSON)",
  mcpPlayParams: "Параметры",
  mcpPlayCall: "Вызвать",
  mcpPlayWrite: "Инструмент записи: вызов по-настоящему изменит реестр проекта.",
  mcpPlayWriteOk: "Понимаю, вызвать",
  mcpPlayBadJson: "Аргументы — не JSON-объект: {error}",
  mcpPlayOk: "✓ ответ за {ms} мс",
  mcpPlayToolError: "✗ инструмент вернул ошибку, {ms} мс",
  mcpPlayFailed: "✗ вызов не прошёл: {error}",
  mcpPlayOut: "→ отправлено",
  mcpPlayIn: "← получено",
  mcpPlayContent: "Содержимое ответа",
  mcpRead: "чтение",
  mcpWrite: "запись",
  mcpToolsTitle: "Инструменты сервера",
  mcpAskTitle: "Что попросить у агента",
  mcpAsk: [
    "«Какие классы держат VmProgram и через какие поля?»",
    "«Опиши все сборки проекта одной строкой каждую, на русском и английском»",
    "«Я переименовал поле — сверь карту и подтверди переименование»",
    "«Покажи на виде Операции связи injects для VmController»",
  ],
};

type Strings = typeof ru;

const en: Strings = {
  navEditor: "Diagrams",
  navExtract: "Extractors",
  navSetup: "Project",
  refresh: "Refresh",
  refreshHint: "Read again from the host",
  noProjectFile: "The host was started with --workspace: no .semaps file, so no extractors or settings.",
  loading: "Loading…",
  setupTitle: "Project settings",
  setupHint: "File {file}. Its comments are kept. Workspace, source root and port apply after semaps restarts.",
  name: "Name",
  workspace: "Workspace",
  sourceRoot: "Source root",
  port: "Port",
  save: "Save",
  saved: "Saved",
  toolsTitle: "Tools",
  shipped: "Beside semaps",
  none: "none",
  runtimeMissing: "not found",
  extractTitle: "Extractors",
  extractHint: "Extract → review the sync report → write. Exactly the facts the report was made from are written.",
  addExtractor: "Add extractor",
  newId: "id of the new extractor (latin, digits, -)",
  language: "Language",
  modelProject: "Model project",
  root: "Root",
  include: "Include",
  exclude: "Exclude",
  edgeKinds: "Edge kinds",
  listHint: "comma-separated",
  command: "Command (file only)",
  extractorFound: "found",
  extractorMissing: "not found",
  remove: "Remove",
  confirmRemove: "Remove extractor “{id}” from .semaps?",
  extract: "Extract",
  running: "Extracting…",
  lastRun: "Last run",
  symbols: "symbols",
  edges: "edges",
  failed: "failed",
  dryRun: "Check the sync",
  apply: "Write to the registry",
  noRenames: "Treat renames as gone + new",
  reportEmpty: "The registry matches the code — nothing to write.",
  written: "Written",
  openEditor: "Open diagrams",
  groups: {
    broken: "broken",
    ambiguous: "ambiguous",
    renames: "rename?",
    gone: "gone",
    added: "missing",
    changed: "changed",
  },
  // mcp
  navMcp: "MCP",
  mcpTitle: "A code map for your AI agent",
  mcpLead:
    "semaps mcp is an MCP server through which Claude Code, Cursor, Copilot and other agents read and edit this map themselves. No need to explain the file format: the agent gets tools, the server keeps the contract's rules.",
  mcpWhyTitle: "What it gives you",
  mcpWhy: [
    "The agent answers architecture questions from the registry instead of rereading the code: who holds VmProgram, what depends on this assembly.",
    "The agent writes descriptions, relation labels and translations itself — all marked authored, with a date.",
    "After a code change the agent runs extraction and sync and explains what changed on the diagrams.",
    "The rules always hold: ids come from the server, nothing is deleted, view layout is touched only when you ask.",
  ],
  mcpStateTitle: "Connection in this project",
  mcpConfigured: "Connected: {file} starts semaps mcp (entry “{entry}”). An agent only has to open this repository.",
  mcpNotConfigured: "Not connected yet: no semaps entry in {file} at the project root.",
  mcpInstall: "Connect",
  mcpInstallHint: "Adds the semaps entry to {file} at the project root; other servers in the file stay.",
  mcpNotOnPath: "semaps is not on PATH: the agent's client will not start it. Install semaps (install.cmd) or write the full path in command.",
  mcpManual: "Or by hand — {file} at the project root:",
  mcpCopy: "Copy",
  mcpCopied: "Copied",
  mcpPlayTitle: "Sandbox",
  mcpPlayHint: "Call a tool on this project the way an agent does, and see what goes out and what comes back. For debugging and growing the server.",
  mcpPlayTool: "Tool",
  mcpPlayArgs: "Arguments (JSON)",
  mcpPlayParams: "Parameters",
  mcpPlayCall: "Call",
  mcpPlayWrite: "A writing tool: the call really changes the project's registry.",
  mcpPlayWriteOk: "I understand, call it",
  mcpPlayBadJson: "Arguments are not a JSON object: {error}",
  mcpPlayOk: "✓ answered in {ms} ms",
  mcpPlayToolError: "✗ the tool returned an error, {ms} ms",
  mcpPlayFailed: "✗ the call failed: {error}",
  mcpPlayOut: "→ sent",
  mcpPlayIn: "← received",
  mcpPlayContent: "Response content",
  mcpRead: "read",
  mcpWrite: "write",
  mcpToolsTitle: "Server tools",
  mcpAskTitle: "What to ask the agent",
  mcpAsk: [
    "“Which classes hold VmProgram, and through which fields?”",
    "“Describe every assembly of the project in one line, in Russian and English”",
    "“I renamed a field — sync the map and confirm the rename”",
    "“Show the injects relations of VmController on the Operations view”",
  ],
};

export const t: Strings = I18nService.get().currentLanguage === "en" ? en : ru;

export function fmt(text: string, values: Record<string, string>): string {
  return text.replace(/\{(\w+)\}/g, (_, k: string) => values[k] ?? "");
}
