import { I18nService } from "../workbench/i18n/I18nService.js";

/**
 * Texts of the tool modes (Extractors, Project). Kept apart from the
 * editor's dictionary.
 */
const ru = {
  navEditor: "Схемы",
  navExtract: "Экстракторы",
  navSetup: "Проект",
  refresh: "Обновить",
  refreshHint: "Перечитать с хоста",
  noProjectFile: "Хост запущен с --workspace: нет файла .semaps, экстракторов и настроек нет.",
  loading: "Загрузка…",
  // setup
  setupTitle: "Настройки проекта",
  setupHint: "Файл {file}. Комментарии в нём сохраняются. Рабочая папка, корень кода и порт вступают в силу после перезапуска semaps.",
  name: "Имя",
  workspace: "Рабочая папка",
  sourceRoot: "Корень кода",
  port: "Порт",
  save: "Сохранить",
  saved: "Сохранено",
  toolsTitle: "Инструменты",
  shipped: "Рядом с semaps",
  none: "нет",
  runtimeMissing: "не найден",
  // extract
  extractTitle: "Экстракторы",
  extractHint: "Извлечь → посмотреть отчёт сверки → записать. Записываются ровно те факты, по которым показан отчёт.",
  addExtractor: "Добавить экстрактор",
  newId: "id нового экстрактора (латиница, цифры, -)",
  language: "Язык",
  modelProject: "Модельный проект",
  root: "Корень",
  include: "Включить",
  exclude: "Исключить",
  edgeKinds: "Виды связей",
  listHint: "через запятую",
  command: "Команда (только в файле)",
  extractorFound: "найден",
  extractorMissing: "не найден",
  remove: "Удалить",
  confirmRemove: "Удалить экстрактор «{id}» из .semaps?",
  extract: "Извлечь",
  running: "Идёт извлечение…",
  lastRun: "Последний прогон",
  symbols: "символов",
  edges: "рёбер",
  failed: "ошибка",
  dryRun: "Проверить сверку",
  apply: "Записать в реестр",
  noRenames: "Переименования — как «пропало + новое»",
  reportEmpty: "Реестр совпадает с кодом — записывать нечего.",
  written: "Записано",
  openEditor: "Открыть схемы",
  groups: {
    broken: "сломано",
    ambiguous: "неоднозначно",
    renames: "переименование?",
    gone: "лишнее",
    added: "не хватает",
    changed: "изменилось",
  },
};

type Strings = typeof ru;

const en: Strings = {
  navEditor: "Diagrams",
  navExtract: "Extractors",
  navSetup: "Project",
  refresh: "Refresh",
  refreshHint: "Read again from the host",
  noProjectFile: "The host was started with --workspace: no .semaps file, so no extractors or settings.",
  loading: "Loading…",
  setupTitle: "Project settings",
  setupHint: "File {file}. Its comments are kept. Workspace, source root and port apply after semaps restarts.",
  name: "Name",
  workspace: "Workspace",
  sourceRoot: "Source root",
  port: "Port",
  save: "Save",
  saved: "Saved",
  toolsTitle: "Tools",
  shipped: "Beside semaps",
  none: "none",
  runtimeMissing: "not found",
  extractTitle: "Extractors",
  extractHint: "Extract → review the sync report → write. Exactly the facts the report was made from are written.",
  addExtractor: "Add extractor",
  newId: "id of the new extractor (latin, digits, -)",
  language: "Language",
  modelProject: "Model project",
  root: "Root",
  include: "Include",
  exclude: "Exclude",
  edgeKinds: "Edge kinds",
  listHint: "comma-separated",
  command: "Command (file only)",
  extractorFound: "found",
  extractorMissing: "not found",
  remove: "Remove",
  confirmRemove: "Remove extractor “{id}” from .semaps?",
  extract: "Extract",
  running: "Extracting…",
  lastRun: "Last run",
  symbols: "symbols",
  edges: "edges",
  failed: "failed",
  dryRun: "Check the sync",
  apply: "Write to the registry",
  noRenames: "Treat renames as gone + new",
  reportEmpty: "The registry matches the code — nothing to write.",
  written: "Written",
  openEditor: "Open diagrams",
  groups: {
    broken: "broken",
    ambiguous: "ambiguous",
    renames: "rename?",
    gone: "gone",
    added: "missing",
    changed: "changed",
  },
};

export const t: Strings = I18nService.get().currentLanguage === "en" ? en : ru;

export function fmt(text: string, values: Record<string, string>): string {
  return text.replace(/\{(\w+)\}/g, (_, k: string) => values[k] ?? "");
}
