import type { CommandDefinition } from "./types.js";
import { i18n } from "../i18n/I18nService.js";
import { fileRealizations } from "../../model/realizations.js";
import {
  openEditProjectDialog,
  openEditViewDialog,
  openNewProjectDialog,
  openNewViewDialog,
} from "../dialogs/WorkspaceDialogs.js";
import { openHelpDialog } from "../dialogs/HelpDialog.js";
import { icons } from "../../ui/icons.js";
import { t as shellStrings } from "../../shell/strings.js";

const ICONS = {
  SAVE: icons.save,
  UNDO: icons.arrowBackUp,
  REDO: icons.arrowForwardUp,
};

export function createBuiltinCommands(): CommandDefinition[] {
  return [
    // ----------------------------------------------------------------- File
    {
      id: "file.save",
      get title() { return i18n.d.commands.save.title; },
      get description() { return i18n.d.commands.save.desc; },
      icon: ICONS.SAVE,
      category: "File",
      shortcut: "Ctrl+S",
      keyTip: "S",
      isEnabled: (ctx) => ctx.editor.hasUnsavedChanges,
      execute: (ctx) => ctx.io.save(),
    },
    {
      id: "file.export.drawio",
      get title() { return i18n.d.commands.exportDrawio.title; },
      get description() { return i18n.d.commands.exportDrawio.desc; },
      icon: icons.fileExport,
      category: "File",
      keyTip: "D",
      isEnabled: (ctx) => ctx.document !== null,
      execute: (ctx) => ctx.io.exportDrawio(),
    },
    {
      id: "file.discard.view",
      title: "Отменить несохранённое у вида",
      description: "Вернуть геометрию открытого вида к файлу",
      icon: icons.arrowBackUp,
      category: "File",
      isEnabled: (ctx) => ctx.editor.currentView !== null,
      execute: (ctx) => ctx.editor.discardCurrentView(),
    },
    {
      id: "file.discard.registry",
      title: "Отменить несохранённое у реестра",
      description: "Вернуть сущности, связи и тексты к файлам",
      icon: icons.arrowBackUp,
      category: "File",
      isEnabled: (ctx) => ctx.editor.currentView !== null,
      execute: (ctx) => ctx.editor.discardRegistry(),
    },

    // ----------------------------------------------------------------- Edit
    {
      id: "edit.undo",
      get title() { return i18n.d.commands.undo.title; },
      get description() { return i18n.d.commands.undo.desc; },
      icon: ICONS.UNDO,
      category: "Edit",
      shortcut: "Ctrl+Z",
      keyTip: "U",
      isEnabled: (ctx) => ctx.history.canUndo,
      execute: (ctx) => ctx.editor.undo(),
    },
    {
      id: "edit.redo",
      get title() { return i18n.d.commands.redo.title; },
      get description() { return i18n.d.commands.redo.desc; },
      icon: ICONS.REDO,
      category: "Edit",
      shortcut: "Ctrl+Y, Ctrl+Shift+Z",
      keyTip: "R",
      isEnabled: (ctx) => ctx.history.canRedo,
      execute: (ctx) => ctx.editor.redo(),
    },
    {
      id: "edit.delete",
      get title() { return i18n.d.commands.deleteSelection.title; },
      get description() { return i18n.d.commands.deleteSelection.desc; },
      icon: icons.trash,
      category: "Edit",
      shortcut: "Delete, Backspace",
      keyTip: "X",
      isEnabled: (ctx) => ctx.selection.hasSelection,
      execute: (ctx) => ctx.editor.deleteSelection(),
    },
    {
      id: "edit.paste",
      get title() { return shellStrings.graphPaste; },
      description: "Вставить узлы, скопированные в режиме «Граф»: только те, что есть в модели; реестр не меняется",
      icon: icons.clipboard,
      category: "Edit",
      shortcut: "Ctrl+V",
      keyTip: "PS",
      isEnabled: (ctx) => ctx.document !== null,
      execute: (ctx) => ctx.editor.pasteGraph(),
    },
    {
      id: "diagram.doc.edit",
      get title() { return i18n.d.dialogs.docEditor.openEditorBtn; },
      get description() { return i18n.d.dialogs.docEditor.editDocTooltip; },
      icon: icons.doc,
      category: "Edit",
      shortcut: "F2, Ctrl+D",
      keyTip: "M",
      isEnabled: (ctx) => ctx.selection.hasSelection,
      execute: (ctx) => ctx.editor.openDocEditor(),
    },
    {
      id: "diagram.code.view",
      title: "Просмотр исходного кода",
      description: "Открыть просмотрщик исходного кода для выбранного элемента",
      icon: icons.code,
      category: "Edit",
      shortcut: "F3, Ctrl+Alt+C",
      keyTip: "C",
      isEnabled: (ctx) => {
        const sel = ctx.canvas.selectedElement();
        return Boolean(sel && fileRealizations(sel.metadata).length > 0);
      },
      execute: (ctx) => ctx.editor.openCodeViewer?.(),
    },

    // -------------------------------------------------------------- Diagram
    {
      id: "diagram.block.add",
      get title() { return i18n.d.commands.createNode.title; },
      get description() { return i18n.d.commands.createNode.desc; },
      icon: icons.plus,
      category: "Diagram",
      shortcut: "Ctrl+Shift+B",
      keyTip: "B",
      isEnabled: (ctx) => ctx.document !== null,
      execute: (ctx) => ctx.editor.createNode(),
    },
    {
      id: "diagram.container.add",
      get title() { return i18n.d.commands.createContainer.title; },
      get description() { return i18n.d.commands.createContainer.desc; },
      icon: icons.box,
      category: "Diagram",
      shortcut: "Ctrl+Shift+Z",
      keyTip: "Z",
      isEnabled: (ctx) => ctx.document !== null,
      execute: (ctx) => ctx.editor.createContainer(),
    },
    {
      id: "diagram.align.left",
      get title() { return i18n.d.commands.alignLeft.title; },
      get description() { return i18n.d.commands.alignLeft.desc; },
      icon: icons.arrowBarToLeft,
      category: "Diagram",
      isEnabled: (ctx) => ctx.canvas.selectedElements().length > 1,
      execute: (ctx) => ctx.editor.alignSelection("left"),
    },
    {
      id: "diagram.align.right",
      get title() { return i18n.d.commands.alignRight.title; },
      get description() { return i18n.d.commands.alignRight.desc; },
      icon: icons.arrowBarToRight,
      category: "Diagram",
      isEnabled: (ctx) => ctx.canvas.selectedElements().length > 1,
      execute: (ctx) => ctx.editor.alignSelection("right"),
    },
    {
      id: "diagram.align.top",
      get title() { return i18n.d.commands.alignTop.title; },
      get description() { return i18n.d.commands.alignTop.desc; },
      icon: icons.arrowBarToUp,
      category: "Diagram",
      isEnabled: (ctx) => ctx.canvas.selectedElements().length > 1,
      execute: (ctx) => ctx.editor.alignSelection("top"),
    },
    {
      id: "diagram.align.bottom",
      get title() { return i18n.d.commands.alignBottom.title; },
      get description() { return i18n.d.commands.alignBottom.desc; },
      icon: icons.arrowBarToDown,
      category: "Diagram",
      isEnabled: (ctx) => ctx.canvas.selectedElements().length > 1,
      execute: (ctx) => ctx.editor.alignSelection("bottom"),
    },
    {
      id: "diagram.align.width",
      get title() { return i18n.d.commands.alignWidth.title; },
      get description() { return i18n.d.commands.alignWidth.desc; },
      icon: icons.arrowsHorizontal,
      category: "Diagram",
      isEnabled: (ctx) => ctx.canvas.selectedElements().length > 1,
      execute: (ctx) => ctx.editor.alignSelection("width"),
    },
    {
      id: "diagram.align.height",
      get title() { return i18n.d.commands.alignHeight.title; },
      get description() { return i18n.d.commands.alignHeight.desc; },
      icon: icons.arrowsVertical,
      category: "Diagram",
      isEnabled: (ctx) => ctx.canvas.selectedElements().length > 1,
      execute: (ctx) => ctx.editor.alignSelection("height"),
    },
    {
      id: "diagram.alignEdge.left",
      get title() { return i18n.d.commands.alignEdgeLeft.title; },
      get description() { return i18n.d.commands.alignEdgeLeft.desc; },
      icon: icons.arrowBarLeft,
      category: "Diagram",
      isEnabled: (ctx) => ctx.canvas.selectedElements().length > 1,
      execute: (ctx) => ctx.editor.alignEdges("left"),
    },
    {
      id: "diagram.alignEdge.right",
      get title() { return i18n.d.commands.alignEdgeRight.title; },
      get description() { return i18n.d.commands.alignEdgeRight.desc; },
      icon: icons.arrowBarRight,
      category: "Diagram",
      isEnabled: (ctx) => ctx.canvas.selectedElements().length > 1,
      execute: (ctx) => ctx.editor.alignEdges("right"),
    },
    {
      id: "diagram.alignEdge.top",
      get title() { return i18n.d.commands.alignEdgeTop.title; },
      get description() { return i18n.d.commands.alignEdgeTop.desc; },
      icon: icons.arrowBarUp,
      category: "Diagram",
      isEnabled: (ctx) => ctx.canvas.selectedElements().length > 1,
      execute: (ctx) => ctx.editor.alignEdges("top"),
    },
    {
      id: "diagram.alignEdge.bottom",
      get title() { return i18n.d.commands.alignEdgeBottom.title; },
      get description() { return i18n.d.commands.alignEdgeBottom.desc; },
      icon: icons.arrowBarDown,
      category: "Diagram",
      isEnabled: (ctx) => ctx.canvas.selectedElements().length > 1,
      execute: (ctx) => ctx.editor.alignEdges("bottom"),
    },
    {
      id: "diagram.ports.set",
      get title() { return i18n.d.commands.portsSet.title; },
      get description() { return i18n.d.commands.portsSet.desc; },
      icon: icons.anchor,
      category: "Diagram",
      keyTip: "P",
      execute: (ctx, args) => ctx.editor.applyPortAssigner(String(args || "uniform")),
    },

    {
      id: "view.strokeScaling.set",
      get title() { return i18n.d.commands.strokeScalingSet.title; },
      get description() { return i18n.d.commands.strokeScalingSet.desc; },
      icon: icons.waveSine,
      category: "View",
      execute: (ctx, args) => ctx.editor.applyStrokeScaling(String(args || "zoom")),
    },

    // ----------------------------------------------------------------- View
    {
      id: "view.grid.toggle",
      get title() { return i18n.d.commands.toggleGrid.title; },
      get description() { return i18n.d.commands.toggleGrid.desc; },
      icon: icons.gridDots,
      category: "View",
      shortcut: "Ctrl+'",
      keyTip: "G",
      isChecked: (ctx) => ctx.canvas.hostElement.classList.contains("with-grid"),
      execute: (ctx) => {
        const next = !ctx.canvas.hostElement.classList.contains("with-grid");
        ctx.editor.applyToggle("grid", next);
      },
    },
    {
      id: "view.routing.debug",
      get title() { return i18n.d.commands.routingDebug.title; },
      get description() { return i18n.d.commands.routingDebug.desc; },
      icon: icons.compass,
      category: "View",
      isChecked: (ctx) => ctx.canvas.debugRouting,
      execute: (ctx) => {
        ctx.canvas.debugRouting = !ctx.canvas.debugRouting;
      },
    },
    {
      id: "view.snap.toggle",
      get title() { return i18n.d.commands.toggleSnap.title; },
      get description() { return i18n.d.commands.toggleSnap.desc; },
      icon: icons.magnet,
      category: "View",
      shortcut: "Ctrl+Shift+S",
      keyTip: "N",
      isChecked: (ctx) => ctx.canvas.gridStep > 0,
      execute: (ctx) => {
        const next = ctx.canvas.gridStep === 0;
        ctx.editor.applyToggle("snap", next);
      },
    },
    {
      id: "view.filters.visual.toggle",
      get title() { return i18n.d.commands.toggleCanvasFilters.title; },
      get description() { return i18n.d.commands.toggleCanvasFilters.desc; },
      icon: icons.sparkles,
      category: "View",
      keyTip: "E",
      execute: (ctx, args) => {
        if (ctx.toggleCanvasFilters) {
          ctx.toggleCanvasFilters(args as HTMLElement | undefined);
        }
      },
    },
    {
      id: "view.shadows.global.toggle",
      get title() { return i18n.d.commands.toggleOverviewShadows.title; },
      get description() { return i18n.d.commands.toggleOverviewShadows.desc; },
      icon: icons.ghost,
      category: "View",
      shortcut: "Ctrl+Shift+G",
      keyTip: "G",
      isChecked: (ctx) => Boolean(ctx.editor.isOverviewShadowsEnabled?.() ?? ctx.canvas.isOverviewShadowsEnabled),
      execute: (ctx) => {
        if (ctx.editor.toggleOverviewShadows) {
          ctx.editor.toggleOverviewShadows();
        } else {
          ctx.canvas.toggleOverviewShadows();
        }
      },
    },
    {
      id: "view.zoom.in",
      get title() { return i18n.d.commands.zoomIn.title; },
      get description() { return i18n.d.commands.zoomIn.desc; },
      icon: icons.zoomIn,
      category: "View",
      shortcut: "Ctrl+=",
      keyTip: "+",
      execute: (ctx) => ctx.canvas.zoomBy(1.2),
    },
    {
      id: "view.zoom.out",
      get title() { return i18n.d.commands.zoomOut.title; },
      get description() { return i18n.d.commands.zoomOut.desc; },
      icon: icons.zoomOut,
      category: "View",
      shortcut: "Ctrl+-",
      keyTip: "-",
      execute: (ctx) => ctx.canvas.zoomBy(0.8),
    },
    {
      id: "view.zoom.reset",
      get title() { return i18n.d.commands.zoomReset.title; },
      get description() { return i18n.d.commands.zoomReset.desc; },
      icon: icons.search,
      category: "View",
      shortcut: "Ctrl+0",
      keyTip: "0",
      execute: (ctx) => ctx.canvas.resetZoom(),
    },
    {
      id: "view.zoom.fit",
      get title() { return i18n.d.commands.fitToScreen.title; },
      get description() { return i18n.d.commands.fitToScreen.desc; },
      icon: icons.maximize,
      category: "View",
      shortcut: "Ctrl+Shift+0",
      keyTip: "F",
      execute: (ctx) => ctx.canvas.fit(),
    },
    {
      id: "view.theme.set",
      get title() { return i18n.d.ribbon.labels.theme; },
      description: "Переключить цветовую тему оформления",
      icon: icons.palette,
      category: "View",
      keyTip: "T",
      execute: (ctx, args) => ctx.editor.applyTheme(String(args || "cream")),
    },
    {
      id: "view.density.set",
      get title() { return i18n.d.commands.densitySet.title; },
      get description() { return i18n.d.commands.densitySet.desc; },
      icon: icons.layoutList,
      category: "View",
      execute: (ctx, args) => ctx.editor.applyDensity(String(args || "norm")),
    },
    {
      id: "view.uiLang.set",
      get title() { return i18n.d.ribbon.labels.uiLang; },
      description: "Переключить язык интерфейса редактора (RU / EN)",
      icon: icons.world,
      category: "View",
      keyTip: "U",
      execute: (ctx, args) => ctx.applyUiLang(String(args || "ru")),
    },
    {
      id: "view.lang.set",
      get title() { return i18n.d.ribbon.labels.dataLang; },
      description: "Переключить язык данных схемы (RU / EN)",
      icon: icons.folders,
      category: "View",
      keyTip: "K",
      execute: (ctx, args) => ctx.editor.applyDataLang(String(args || "ru")),
    },
    {
      id: "view.edges.toggleStructure",
      get title() { return i18n.d.commands.toggleStructureEdges.title; },
      get description() { return i18n.d.commands.toggleStructureEdges.desc; },
      icon: icons.link,
      category: "View",
      keyTip: "E",
      isChecked: (ctx) => !ctx.canvas.isEdgeFamilyHidden("structure"),
      execute: (ctx) => {
        const isHidden = ctx.canvas.isEdgeFamilyHidden("structure");
        ctx.editor.applyToggle("structure-edges", isHidden);
      },
    },

    // --------------------------------------------------------------- Panels
    {
      id: "panel.properties.toggle",
      get title() { return i18n.d.panels.properties.title; },
      get description() { return i18n.d.commands.toggleProperties.desc; },
      icon: icons.settings,
      category: "Panels",
      shortcut: "Alt+1",
      keyTip: "P1",
      isChecked: (ctx) => ctx.panels.isVisible("properties"),
      execute: (ctx) => ctx.panels.toggle("properties"),
    },
    {
      id: "panel.relations.toggle",
      get title() { return i18n.d.panels.relations.title; },
      get description() { return i18n.d.commands.toggleRelations.desc; },
      icon: icons.link,
      category: "Panels",
      shortcut: "Alt+2",
      keyTip: "P2",
      isChecked: (ctx) => ctx.panels.isVisible("relations"),
      execute: (ctx) => ctx.panels.toggle("relations"),
    },
    {
      id: "panel.filters.toggle",
      get title() { return i18n.d.panels.filters.title; },
      get description() { return i18n.d.commands.toggleFilters.desc; },
      icon: icons.filter,
      category: "Panels",
      shortcut: "Alt+3",
      keyTip: "P3",
      isChecked: (ctx) => ctx.panels.isVisible("filters"),
      execute: (ctx) => ctx.panels.toggle("filters"),
    },
    {
      id: "panel.styles.toggle",
      get title() { return i18n.d.panels.styles.title; },
      get description() { return i18n.d.commands.toggleStyles.desc; },
      icon: icons.palette,
      category: "Panels",
      shortcut: "Alt+4",
      keyTip: "P4",
      isChecked: (ctx) => ctx.panels.isVisible("styles"),
      execute: (ctx) => ctx.panels.toggle("styles"),
    },
    {
      id: "panel.catalog.toggle",
      get title() { return i18n.d.panels.catalog.title; },
      get description() { return i18n.d.commands.toggleCatalog.desc; },
      icon: icons.books,
      category: "Panels",
      shortcut: "Alt+5",
      keyTip: "P5",
      isChecked: (ctx) => ctx.panels.isVisible("catalog"),
      execute: (ctx) => ctx.panels.toggle("catalog"),
    },
    {
      id: "panel.changes.toggle",
      get title() { return i18n.d.panels.changes.title; },
      get description() { return i18n.d.commands.toggleChanges.desc; },
      icon: icons.checks,
      category: "Panels",
      shortcut: "Alt+8",
      keyTip: "P8",
      isChecked: (ctx) => ctx.panels.isVisible("changes"),
      execute: (ctx) => ctx.panels.toggle("changes"),
    },
    {
      id: "panel.base.toggle",
      get title() { return i18n.d.panels.base.title; },
      get description() { return i18n.d.commands.toggleBase.desc; },
      icon: icons.database,
      category: "Panels",
      shortcut: "Alt+6",
      keyTip: "P6",
      isChecked: (ctx) => ctx.panels.isVisible("base"),
      execute: (ctx) => ctx.panels.toggle("base"),
    },
    {
      id: "panel.neighbourhood.toggle",
      get title() { return i18n.d.panels.neighbourhood.title; },
      get description() { return i18n.d.commands.toggleNeighbourhood.desc; },
      icon: icons.hierarchy,
      category: "Panels",
      shortcut: "Alt+7",
      keyTip: "P7",
      isChecked: (ctx) => ctx.panels.isVisible("neighbourhood"),
      execute: (ctx) => ctx.panels.toggle("neighbourhood"),
    },

    // ------------------------------------------------------------ Workspace
    {
      id: "workspace.project.new",
      get title() { return i18n.d.commands.newProject.title; },
      get description() { return i18n.d.commands.newProject.desc; },
      icon: icons.folder,
      category: "Workspace",
      keyTip: "P",
      execute: (ctx) => openNewProjectDialog(ctx.editor),
    },
    {
      id: "workspace.view.new",
      get title() { return i18n.d.commands.newView.title; },
      get description() { return i18n.d.commands.newView.desc; },
      icon: icons.map,
      category: "Workspace",
      keyTip: "S",
      execute: (ctx) => openNewViewDialog(ctx.editor),
    },
    {
      id: "workspace.project.edit",
      get title() { return i18n.d.commands.editProject.title; },
      get description() { return i18n.d.commands.editProject.desc; },
      icon: icons.pencil,
      category: "Workspace",
      keyTip: "E",
      isEnabled: (ctx) => ctx.editor.currentView !== null,
      execute: (ctx) => {
        const project = ctx.editor.currentView ? ctx.editor.projectOf(ctx.editor.currentView) : undefined;
        if (project) openEditProjectDialog(ctx.editor, project);
      },
    },
    {
      id: "workspace.view.edit",
      get title() { return i18n.d.commands.editView.title; },
      get description() { return i18n.d.commands.editView.desc; },
      icon: icons.notes,
      category: "Workspace",
      keyTip: "W",
      isEnabled: (ctx) => ctx.editor.currentView !== null,
      execute: (ctx) => {
        if (ctx.editor.currentView) openEditViewDialog(ctx.editor, ctx.editor.currentView);
      },
    },
    {
      id: "help.structure",
      get title() { return i18n.d.commands.helpStructure.title; },
      get description() { return i18n.d.commands.helpStructure.desc; },
      icon: icons.compass,
      category: "Help",
      shortcut: "F1",
      keyTip: "H",
      execute: () => openHelpDialog(),
    },
    {
      id: "workspace.layout.reset",
      get title() { return i18n.d.commands.resetLayout.title; },
      get description() { return i18n.d.commands.resetLayout.desc; },
      icon: icons.refresh,
      category: "Workspace",
      keyTip: "WR",
      execute: (ctx) => ctx.workspace.resetLayout(),
    },
  ];
}
